FORMAT: 1A
HOST: https://sendit-dera.herokuapp.com/api/v1

# Sendit API

SendIT is a courier service that helps users deliver parcels to different destinations.
For the github link: please click [link](https://github.com/Je-ni/SendIT)
For the interactive API, please click [link](https://senditdera.docs.apiary.io/#)

# Group Users

## List all users [GET /users]

This requires an admin authorisation token for access.

+ Request

    + Headers
    
            x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiNDU0NTFiLTljMDctNGVjMi1hOTU3LTg2OTUwZDZjNzgwYiIsImFkbWluIjp0cnVlLCJpYXQiOjE1NDUzNDE0MTcsImV4cCI6MTU0NzkzMzQxN30.YXWbAoxIu03ffnVnbuKxzAWKtAH33455fmmpLtPWtJo

+ Response 200 (application/json)

        {
            "status": 200,
            "data": [
                {
                    "id": "bee35568-1282-4e3b-9bdf-2cd02861fed2",
                    "firstname": "chidera",
                    "lastname": "olibie",
                    "othernames": "jennifer",
                    "password": "cc493644d129c078912b03a1bf0ec2516e26e286cc9a72c5f84661eb6425fac3",
                    "email": "chideraolibie1@gmail.com",
                    "username": "joc123",
                    "registered": "2018-12-10T23:00:00.000Z",
                    "isadmin": false,
                    "createddate": "2018-12-11T20:42:44.108Z",
                    "modifieddate": "2018-12-11T20:42:44.108Z"
                },
                ...
            ]
        }
        
+ Response 401 (application/json)

        {
            "status": 401,
            "error": "user auth failed"
        }

## User signup [POST /users/auth/signup]

+ Request (application/json)

        {
            "firstname": "chinny",
            "lastname": "olibie",
            "othernames": "jennifer",
            "username": "oli",
            "email": "chideraoli@gmail.com",
            "password": "chisom"
        }

+ Response 201 (application/json)

        {
            "status": 201,
            "data": [
                {
                    "id": "e43db395-c3b3-442e-acea-4abf7222d244",
                    "firstname": "chinny",
                    "lastname": "olibie",
                    "othernames": "jennifer",
                    "password": "cc493644d129c078912b03a1bf0ec2516e26e286cc9a72c5f84661eb6425fac3",
                    "email": "chideraoli@gmail.com",
                    "username": "oli",
                    "registered": "2019-01-05T23:00:00.000Z",
                    "isadmin": false,
                    "createddate": "2019-01-06T16:31:15.511Z",
                    "modifieddate": "2019-01-06T16:31:15.511Z"
                }
            ]
        }

+ Response 409 (application/json)

        {
            "status": 409,
            "error": "Username already exists"
        }
        
## User login [POST /users/auth/login]

+ Request (application/json)

        {
            "email": "chideraoli@gmail.com",
            "password": "chisom"
        }

+ Response 200 (application/json)

        {
            "status": 200,
            "data": [
                {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0M2RiMzk1LWMzYjMtNDQyZS1hY2VhLTRhYmY3MjIyZDI0NCIsImVtYWlsIjoiY2hpZGVyYW9saUBnbWFpbC5jb20iLCJpYXQiOjE1NDY3OTMwODksImV4cCI6MTU0OTM4NTA4OX0.T2NviAC4l_f8DZCWK1ocES31ot__XHNosc_5yUwrAN8",
                    "user": {
                        "id": "e43db395-c3b3-442e-acea-4abf7222d244",
                        "firstname": "chinny",
                        "lastname": "olibie",
                        "othernames": "jennifer",
                        "password": "cc493644d129c078912b03a1bf0ec2516e26e286cc9a72c5f84661eb6425fac3",
                        "email": "chideraoli@gmail.com",
                        "username": "oli",
                        "registered": "2019-01-05T23:00:00.000Z",
                        "isadmin": false,
                        "createddate": "2019-01-06T16:31:15.511Z",
                        "modifieddate": "2019-01-06T16:31:15.511Z"
                    }
                }
            ]
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "error": "Email/Password Incorrect"
        }

## User parcels [GET /users/{placedby}/parcels]

This requires either admin authentication or user authentication

+ Parameter

    + placedby (UUID) - id of the user in the form of a UUID

+ Request (application/json)

    + Headers
        
            x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6I...


+ Response 200 (application/json)

        {
            "status": 200,
            "data": [
                {
                    "id": "97543e4d-d4d8-4d41-9221-f06f0c734590",
                    "placedby": "df863d82-ee86-4c50-abe9-a270ee8c7855",
                    "weight": 70,
                    "weightmetric": "kg",
                    "senton": "2018-12-13T13:01:39.379Z",
                    "deliveredon": null,
                    "status": "placed",
                    "active": true,
                    "currentlocation": "lagos",
                    "sentfrom": "lagos",
                    "sentto": "niger",
                    "description": "just send"
                }
            ]
        }
        
# Group Parcels

## All parcels [/parcels]

### Create parcels [POST]
It is required that user be logged in or admin access. 

+ Request (application/json)

    + Headers

            x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJlZTM1NTY4LTEyODItNGUzYi05YmRmLTJjZDAyODYxZmVkMiIsImlhdCI6MTU0NDY0NTM1MSwiZXhwIjoxNTQ3MjM3MzUxfQ.0BI9iw7tKISxrPwYz_uBd78P40fZnWGmvdOe16czqqc

    + Body
    
            {
                "weight": "100.23",
                "sentfrom": "zamfara",
                "sentto": "niger",
                "description": "kidney",
                "weightmetric": "kg"
            }
            
+ Response 201 (application/json)

        {
            "status": 201,
            "data": [
                { 
                    "id": "1de87067-3790-46fe-a744-49285772b453",
                    "message": "Order created"
                }
            ] 
        }

+ Response 500 (application/json)

        {
            "status": 500,
            "error": {
                "name": "error",
                "length": 351,
                "severity": "ERROR",
                "code": "23503",
                "detail": "Key (placedby)=(48cdacb9-98f8-459e-a8f3-ddc11c8c2a4d) is not present in table \"users\".",
                "schema": "public",
                "table": "parcels",
                "constraint": "parcels_placedby_fkey",
                "file": "d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\ri_triggers.c",
                "line": "2851",
                "routine": "ri_ReportViolation"
            }
        }

### Get parcels [GET]
Admin access only. 

+ Request (application/json)

    + Headers

            x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiNDU0NTFiLTljMDctNGVjMi1hOTU3LTg2OTUwZDZjNzgwYiIsImFkbWluIjp0cnVlLCJpYXQiOjE1NDUzNDE0MTcsImV4cCI6MTU0NzkzMzQxN30.YXWbAoxIu03ffnVnbuKxzAWKtAH33455fmmpLtPWtJo
            
+ Response 200 (application/json)

        {
            "status": 200,
            "data": [
                {
                    "id": "cd1e0667-4c0f-4ff2-8af2-b323eefdb492",
                    "placedby": "a4c1a330-8477-4b52-b7cf-ef290a0bbc1f",
                    "weight": 20.4,
                    "weightmetric": "kg",
                    "senton": "2018-12-22T02:19:12.732Z",
                    "currentlocation": "Aba",
                    "sentfrom": "ghana",
                    "sentto": "Akure",
                    "description": "black shoe",
                    "username": "chiric",
                    "email": "jenniferolibie@gmail.com"
                }
            ]
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "error": "user auth failed"
        }

## Single parcel [/parcels/{parcelId}]

+ Parameter

    + parcelId (UUID) - id of the parcel in the form of a UUID
    
### Get parcel by id [GET]

+ Request (application/json)

    + Headers

            x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiNDU0NTFiLTljMDctNGVjMi1hOTU3LTg2OTUwZDZjNzgwYiIsImFkbWluIjp0cnVlLCJpYXQiOjE1NDUzNDE0MTcsImV4cCI6MTU0NzkzMzQxN30.YXWbAoxIu03ffnVnbuKxzAWKtAH33455fmmpLtPWtJo
            
+ Response 200 (application/json)

        {
            "status": 200,
            "data": [
                {
                    "id": "cd1e0667-4c0f-4ff2-8af2-b323eefdb492",
                    "placedby": "a4c1a330-8477-4b52-b7cf-ef290a0bbc1f",
                    "weight": 20.4,
                    "weightmetric": "kg",
                    "senton": "2018-12-22T02:19:12.732Z",
                    "currentlocation": "Aba",
                    "sentfrom": "ghana",
                    "sentto": "Akure",
                    "description": "black shoe",
                    "username": "chiric",
                    "email": "jenniferolibie@gmail.com"
                }
            ]
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "error": "user auth failed"
        }

## Change parcel status [PATCH /parcels/{parcelId}/status]

+ Parameter

    + parcelId (UUID) - id of the parcel in the form of a UUID

+ Request (application/json)

    + Headers

            x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiNDU0NTFiLTljMDctNGVjMi1hOTU3LTg2OTUwZDZjNzgwYiIsImFkbWluIjp0cnVlLCJpYXQiOjE1NDUzNDE0MTcsImV4cCI6MTU0NzkzMzQxN30.YXWbAoxIu03ffnVnbuKxzAWKtAH33455fmmpLtPWtJo
    
    + Body
    
            {
                "status": "delivered"
            }
                  
+ Response 200 (application/json)

        {
            "status": 200,
            "data": [
                {
                    "id": "a66a1bf6-92ba-4147-af77-f262b5024a5f",
                    "status": "delivered",
                    "message": "Parcel Status Updated"
                }
            ]
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "error": "user auth failed"
        }

## Change parcel destination [PATCH /parcels/{parcelId}/destination]

+ Parameter

    + parcelId (UUID) - id of the parcel in the form of a UUID

+ Request (application/json)

    + Headers

            x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiNDU0NTFiLTljMDctNGVjMi1hOTU3LTg2OTUwZDZjNzgwYiIsImFkbWluIjp0cnVlLCJpYXQiOjE1NDUzNDE0MTcsImV4cCI6MTU0NzkzMzQxN30.YXWbAoxIu03ffnVnbuKxzAWKtAH33455fmmpLtPWtJo
    
    + Body
    
            {
                "sentto": "akure"
            }
            
+ Response 200 (application/json)

        {
            "status": 200,
            "data": [
                {
                    "id": "a66a1bf6-92ba-4147-af77-f262b5024a5f",
                    "sentto": "akure",
                    "message": "Parcel destination changed"
                }
            ]
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "error": "user auth failed"
        }

+ Response 409 (application/json)

        {
            "status": 409,
            "error": "action not allowed. Parcel already delivered"
        }

## Change parcel current location [PATCH /parcels/{parcelId}/currentlocation]

+ Parameter

    + parcelId (UUID) - id of the parcel in the form of a UUID

+ Request (application/json)

    + Headers

            x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiNDU0NTFiLTljMDctNGVjMi1hOTU3LTg2OTUwZDZjNzgwYiIsImFkbWluIjp0cnVlLCJpYXQiOjE1NDUzNDE0MTcsImV4cCI6MTU0NzkzMzQxN30.YXWbAoxIu03ffnVnbuKxzAWKtAH33455fmmpLtPWtJo
    
    + Body
    
            {
                "currentlocation": "india"
            }
            
+ Response 200 (application/json)

        {
            "status": 200,
            "data": [
                {
                    "id": "a66a1bf6-92ba-4147-af77-f262b5024a5f",
                    "currentlocation": "india",
                    "message": "Parcel location updated"
                }
            ]
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "error": "user auth failed"
        }

+ Response 404 (application/json)

        {
            "status": 404,
            "error": "Parcel not found"
        }

## Cancel parcel order [PATCH /parcels/{parcelId}/cancel]

+ Parameter

    + parcelId (UUID) - id of the parcel in the form of a UUID

+ Request (application/json)

    + Headers

            x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiNDU0NTFiLTljMDctNGVjMi1hOTU3LTg2OTUwZDZjNzgwYiIsImFkbWluIjp0cnVlLCJpYXQiOjE1NDUzNDE0MTcsImV4cCI6MTU0NzkzMzQxN30.YXWbAoxIu03ffnVnbuKxzAWKtAH33455fmmpLtPWtJo
    
+ Response 200 (application/json)

        {
            "status": 200,
            "data": [
                {
                    "id": "a66a1bf6-92ba-4147-af77-f262b5024a5f",
                    "active": "false",
                    "message": "Parcel order cancelled"
                }
            ]
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "error": "user auth failed"
        }

+ Response 404 (application/json)

        {
            "status": 404,
            "error": "Parcel not found"
        }

# Group Admin

## Login [POST /admin/auth/login]

+ Request (application/json)

        {
            "name": "superadmin",
            "password": "admin"
        }
            
+ Response 200 (application/json)

        {
            "status": 200,
            "data": [
                {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiNDU0NTFiLTljMDctNGVjMi1hOTU3LTg2OTUwZDZjNzgwYiIsImFkbWluIjp0cnVlLCJpYXQiOjE1NDY5MDM1MjAsImV4cCI6MTU0OTQ5NTUyMH0._mhmhyMiPPQCuWyAFXfEZII6JpOrB8eBnzaRFcy4h5M",
                    "user": {
                        "id": "0b45451b-9c07-4ec2-a957-86950d6c780b",
                        "name": "superadmin",
                        "email": "b2comicscrum@gmail.com",
                        "password": "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                        "createddate": "2018-12-18T16:40:30.296Z",
                        "modifieddate": "2018-12-18T16:40:30.296Z"
                    }
                }
            ]
        }